<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Master Store</name>
   <tag></tag>
   <elementGuidId>a3a40c4a-afd1-447d-b842-21c5b484ca43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='n6GQlb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#n6GQlb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0b2aaa6d-46d4-45b1-904c-e6d1eb451b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>n6GQlb</value>
      <webElementGuid>ce680372-4bb4-4fed-9458-14b253571406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-a</value>
      <webElementGuid>330de57d-2028-4a1d-86b9-c84a84003148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.zul?inc=/userManagement/customer/index.zul</value>
      <webElementGuid>57ed0a88-0006-4c35-99f8-b5b15fd4fa5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Store</value>
      <webElementGuid>368f1db2-45a5-4bc1-b5e2-ffca7f041cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n6GQlb&quot;)</value>
      <webElementGuid>1762a9ac-2f51-4c57-93b4-521dff64fdc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='n6GQlb']</value>
      <webElementGuid>32961973-ddc8-48cc-978f-f0589a349f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='n6GQkb-cave']/a</value>
      <webElementGuid>312200a4-017b-4a5a-a146-92b6dd071adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Master Store')]</value>
      <webElementGuid>e655550d-91bb-4685-9451-e39a1c342b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Management'])[1]/following::a[1]</value>
      <webElementGuid>e0513722-d055-47a5-8f4a-349fe9e60faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dismiss All'])[1]/following::a[3]</value>
      <webElementGuid>28fb5010-0bbe-4009-bd09-54b767eeec38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master User'])[1]/preceding::a[1]</value>
      <webElementGuid>3c62ded4-c5ec-4004-9722-918135d68e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role and Menu'])[1]/preceding::a[2]</value>
      <webElementGuid>e2adc695-4419-4da0-85a5-d9f1695cfdb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Master Store']/parent::*</value>
      <webElementGuid>c32d5252-7789-44d1-a86e-88e32492b651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.zul?inc=/userManagement/customer/index.zul')]</value>
      <webElementGuid>092eda46-d846-4620-81cc-63a2ec748a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/a</value>
      <webElementGuid>741de09f-3ef3-4888-8b15-0f1b163f1068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'n6GQlb' and @href = 'index.zul?inc=/userManagement/customer/index.zul' and (text() = 'Master Store' or . = 'Master Store')]</value>
      <webElementGuid>45f9955c-1374-4304-aacd-8100f1a3ab8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
