<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LOG IN_o5FQ9</name>
   <tag></tag>
   <elementGuidId>10132023-3de6-4bc7-9f81-dc0765fa5b9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='o5FQ9']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'o5FQ9' and @type = 'text' and @placeholder = 'Username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#o5FQ9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb6815e4-a5e6-4a23-8311-bc4992e6553a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o5FQ9</value>
      <webElementGuid>c763758b-abd8-4ab7-a698-995291923a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox</value>
      <webElementGuid>58f7f0f0-ee05-4433-9b37-6e34adefeb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>466b5c8f-3170-4788-bae3-d2fac33a8b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>9e801e0a-a128-459b-ae6d-4899dd72d6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o5FQ9&quot;)</value>
      <webElementGuid>23a0c3e1-372c-4421-90e2-de326366046a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='o5FQ9']</value>
      <webElementGuid>7ea8cb59-9bd8-4cb8-8ddc-e9284d105b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='o5FQ8']/input</value>
      <webElementGuid>522f139f-a6cb-42ee-9988-70f24ccb4ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f242947b-da33-4631-a173-1fea8f3f90a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'o5FQ9' and @type = 'text' and @placeholder = 'Username']</value>
      <webElementGuid>1a751704-69f2-4ff7-ad5f-2cc1c698b728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
